---
apiVersion: v1
kind: Service
metadata:
  name: argo-server
  labels:
    {{- include "my_argo.labels" . | nindent 4 }}
spec:
  ports:
  - name: web
    port: 2746
    targetPort: 2746
  selector:
    app: argo-server
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-controller-metrics
  labels:
    {{- include "my_argo.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: workflow-controller
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    {{- include "my_argo.labels" . | nindent 4 }}
  name: minio
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    {{- include "my_argo.labels" . | nindent 4 }}
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
