---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  labels:
{{ include "my_argo.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
  labels:
{{ include "my_argo.labels" . | nindent 4 }}
