apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-retry
spec:
  entrypoint: diamond
  templates:
  - name: stps
    steps:
      - - name: A
          template: echo
          arguments:
            parameters: [{name: message, value: A}]
      - - name: B
          template: echo
          arguments:
            parameters: [{name: message, value: B}]
      - - name: C
          template: echo
          arguments:
            parameters: [{name: message, value: C}]
  - name: echo
    inputs:
      parameters:
      - name: message
    script:
      image: hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.13_2.13.3
      command: [scala]
      source: |
        if ("{{inputs.parameters.message}}" == "B") sys.exit(1)
        else println("{{inputs.parameters.message}}")
